kind: pipeline
type: docker
name: 阿里云Tonken
node:
  server: USA
clone:
  disable: true
steps:
- name: 初始化环境
  image: chaikair/dockeri:latest
  volumes:
  - name: cache
    path: /vue
  - name: docker-sock
    path: /var/run/docker.sock
  failure: ignore
  commands:
  - docker stop test
  - docker rm test
  - docker image prune -f
  - docker volume prune -f
- name: 拉取项目
  image: alpine
  volumes:
  - name: cache
    path: /vue
  commands:
  - apk update
  - apk add git bash
  - cd /vue
  - git clone https://github.com/20020314/aliyundriver-refresh-token.git
- name: 安装依赖
  image: node:16.15.0
  volumes:
  - name: cache
    path: /vue
  commands:
  - cd /vue/aliyundriver-refresh-token
  - npm install vite
  - npx vite build
- name: 运行
  image: chaikair/dockeri
  volumes:
  - name: cache
    path: /vue/
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - cd /vue/aliyundriver-refresh-token/ 
  - docker build -t alitoken:v1 .
  - docker run --name test -d -p 8081:80 alitoken:v1
# 声明路径
volumes:
- name: cache
  temp: {}
- name: docker-sock
  host:
  path: /var/run/docker.sock
