kind: pipeline
type: docker
name: Build
clone:
  disable: true
steps:
- name: 拉取项目
  image: alpine
  volumes:
  - name: cache
    path: /vue
  commands:
  - apk update
  - apk add git bash
  - cd /vue
  - git clone https://github.com/20020314/aliyundriver-refresh-token.git

- name: 安装依赖
  image: node:16.15.0
  volumes:
  - name: cache
    path: /vue
  commands:
  - cd /vue/aliyundriver-refresh-token
  - npm init @vitejs/app
  - vite build



volumes:
- name: cache
  temp: {}
