kind: pipeline
type: docker
name: Build
clone:
  disable: true
steps:
- name: 拉取项目
  image: alpine
  volumes:
  - name: cache
    path: /vue
  commands:
  - apk update
  - apk add git bash
  - cd /vue
  - git clone https://github.com/20020314/aliyundriver-refresh-token.git

- name: 安装依赖
  image: python:3-alpine
  volumes:
  - name: cache
    path: /python
  commands:
  - cd /python/AutoMihoyoBBS
  - pip install -r requirements.txt
  - pip install PyYAML
  - python3 main.py



volumes:
- name: cache
  temp: {}
