version: 18
jobs:
- name: ☁️同步
  steps:
  - !PushRepository
    name: Sync
    remoteUrl: https://github.com/20020314/aliyundriver-refresh-token
    userName: '20020314'
    passwordSecret: Token
    withLfs: false
    force: true
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: 构建
  steps:
  - !CommandStep
    name: Build
    runInContainer: true
    image: node:16.17.1-alpine
    interpreter: !DefaultInterpreter
      commands:
      - apk update
      - apk add git bash
      - cd /onedev-build
      - git clone https://github.com/20020314/aliyundriver-refresh-token.git
      - cd /onedev-build/aliyundriver-refresh-token
      - npm install vite
      - npx vite build
    useTTY: true
    condition: ALWAYS
  - !CommandStep
    name: docker
    runInContainer: true
    image: chaikair/dockeri:latest
    interpreter: !DefaultInterpreter
      commands:
      - cd /onedev-build/aliyundriver-refresh-token
      - docker build -t chaikair/aliyuntoken:1.0 .
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Start
    runInContainer: true
    image: chaikair/dockeri:latest
    interpreter: !DefaultInterpreter
      commands:
      - docker run --name test -d -p 4030:80 chaikair/aliyuntoken:1.0
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: 停止
  steps:
  - !CommandStep
    name: Stop
    runInContainer: true
    image: chaikair/dockeri:latest
    interpreter: !DefaultInterpreter
      commands:
      - docker stop test
      - docker rm test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
