version: 18
jobs:
- name: ☁️同步
  steps:
  - !PushRepository
    name: Sync
    remoteUrl: https://github.com/20020314/aliyundriver-refresh-token
    userName: '20020314'
    passwordSecret: Token
    withLfs: false
    force: true
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: 构建
  steps:
  - !CommandStep
    name: Git
    runInContainer: true
    image: chaikair/dockeri:latest
    interpreter: !DefaultInterpreter
      commands:
      - apk add git
      - git clone https://github.com/20020314/aliyundriver-refresh-token
      - cd ali*
      - docker build -t aliyun:1.0 .
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
